<a href="https://colab.research.google.com/github/Fegel12/Unab/blob/main/1_2_Pandas_Fergel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



<img src="https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/102012/logo_unab.png?itok=hZ5x30O2" width="240" height="240" align="right"/>

<center><h1>Estadística para la Ciencia de Datos</header1></center>
<left><h1>Unidad 1: Análisis exploratorio de datos</header1></left>

# Pandas

In [ ]:
# paquetes necesarios en esta sección
import pandas as pd

Los datasets de prueba que se van a utilizar en esta sección fueron obtenidos de Kaggle.
- [Customer Churn Classification](https://www.kaggle.com/datasets/saisiddartha69/customer-churn-classification)

Los datasets han sido descargados y se han llevado a GIT, de ahí se van a extraer

Acá vienen los enlaces

In [ ]:
print(path)

https://raw.githubusercontent.com/JSebasB90/datasets/refs/heads/main/Customer%20Churn.csv

In [ ]:
# CSV de Customer Churn
path = 'https://raw.githubusercontent.com/JSebasB90/datasets/refs/heads/main/Customer%20Churn.csv'

**Pandas** es una biblioteca de Python diseñada para facilitar la manipulación y análisis de datos estructurados, como tablas y series temporales. Proporciona estructuras de datos flexibles, como DataFrames y Series, que permiten realizar operaciones eficientes para limpiar, transformar, filtrar, agregar y visualizar datos. Con pandas, es posible cargar archivos de diferentes formatos (CSV, Excel, JSON, etc.), manipular grandes volúmenes de datos, realizar análisis estadísticos y preparar los datos para su uso en machine learning u otras aplicaciones analíticas.

Se recomienda revisar la documentación oficial de [Pandas](https://pandas.pydata.org/docs/index.html)

### Lectura de dataset

In [ ]:
pd.read_csv(path)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df = pd.read_csv(path)

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [ ]:
df.tail(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4711,4712,15758831,Thornton,754,France,Male,39,3,74896.33,1,0,0,34430.16,0
9566,9567,15743193,Olson,644,France,Male,37,6,117271.80,2,1,0,104217.96,1
3584,3585,15664227,Threatt,506,Germany,Male,28,8,53053.76,1,0,1,24577.34,0
9627,9628,15689322,Bevan,641,Spain,Male,31,3,153316.14,1,1,0,59927.99,0
3191,3192,15760570,Stephenson,590,France,Male,32,5,0.00,2,1,0,59249.83,0
2676,2677,15641994,Meng,667,Germany,Male,43,1,103018.45,1,1,0,32462.39,1
2534,2535,15803804,Walker,717,Germany,Female,35,5,103214.71,1,1,0,172172.70,0
438,439,15783501,Findlay,800,France,Female,38,2,168190.33,2,1,0,68052.08,0
8678,8679,15633227,Kenechukwu,518,France,Female,28,9,85146.36,1,0,0,2803.89,0
6287,6288,15668289,McWilliams,690,Spain,Male,32,2,76087.98,1,0,1,151822.66,0

In [ ]:
df.sample(10, random_state=2024)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
8374,8375,15646720,Tsui,628,Spain,Female,55,7,0.00,3,1,0,85890.75,1
6935,6936,15750396,McKissick,670,France,Male,33,1,0.00,2,1,1,86413.11,0
5103,5104,15808526,Cartwright,783,Germany,Female,58,3,127539.30,1,1,1,96590.39,1
8963,8964,15796993,McCollum,741,France,Male,52,1,171236.30,2,0,0,21834.40,1
4993,4994,15728912,Swanson,554,France,Female,44,6,92436.86,1,1,0,126033.90,0
9069,9070,15777459,Gordon,619,Spain,Female,32,4,175406.13,2,1,1,172792.43,1
3924,3925,15732334,Black,653,France,Female,40,0,0.00,2,1,0,35795.85,0
399,400,15646372,Outhwaite,616,France,Female,66,1,135842.41,1,1,0,183840.51,1
6863,6864,15765732,Simmons,564,Spain,Female,24,6,149592.14,1,1,1,153771.80,0
7440,7441,15604130,Johnstone,622,Spain,Female,47,6,142319.03,1,0,0,100183.05,0

In [ ]:
df.sample(10, random_state=2024).shape

(10, 14)

In [ ]:
df.sample(10, random_state=2024).index

Index([8374, 6935, 5103, 8963, 4993, 9069, 3924, 399, 6863, 7440], dtype='int64')

In [ ]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
help(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
Help on NoneType object:

class NoneType(object)
 |  Methods defined here:
 |
 |  __bool__(self, /)
 |      True if self else False
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
df.values

array([[1, 15634602, 'Hargrave', ..., 1, 101348.88, 1],
       [2, 15647311, 'Hill', ..., 1, 112542.58, 0],
       [3, 15619304, 'Onio', ..., 0, 113931.57, 1],
       ...,
       [9998, 15584532, 'Liu', ..., 1, 42085.58, 1],
       [9999, 15682355, 'Sabbatini', ..., 0, 92888.52, 1],
       [10000, 15628319, 'Walker', ..., 0, 38190.78, 0]], dtype=object)

In [ ]:
df.values[10]

array([11, 15767821, 'Bearce', 528, 'France', 'Male', 31, 6, 102016.72, 2,
       0, 0, 80181.12, 0], dtype=object)

In [ ]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
# imprime las últimas 5 filas
df.tail(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.sample(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2943,2944,15639277,Lin,678,France,Female,41,9,0.00,1,0,0,13160.03,0
1092,1093,15585198,Bergamaschi,715,France,Male,41,4,94267.90,1,0,1,152821.12,1
3893,3894,15664802,Chinweuba,543,France,Female,42,5,0.00,2,0,0,101905.34,0
1480,1481,15716822,Moen,646,France,Male,30,5,98014.74,1,1,1,12757.14,0
9917,9918,15755731,Davis,635,Germany,Male,53,8,117005.55,1,0,1,123646.57,1

## Orden y subconjuntos

In [ ]:
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

Vamos a ordenar por la columna 'Age'

In [ ]:
df.sort_values('Age')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1678,1679,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
4556,4557,15796231,Nwankwo,681,France,Female,18,1,98894.39,1,1,1,9596.40,0
9520,9521,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
9526,9527,15665521,Chiazagomekpele,642,Germany,Male,18,5,111183.53,2,0,1,10063.75,0
9572,9573,15641688,Collier,644,Spain,Male,18,7,0.00,1,0,1,59645.24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3531,3532,15653251,Hickey,408,France,Female,84,8,87873.39,1,0,0,188484.52,1
3033,3034,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
2458,2459,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
6443,6444,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0
6759,6760,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0

In [ ]:
# ordenar en orden contrario
df.sort_values('Age', ascending=False)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
6759,6760,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0
6443,6444,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0
2458,2459,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
3033,3034,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
3531,3532,15653251,Hickey,408,France,Female,84,8,87873.39,1,0,0,188484.52,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7722,7723,15570086,Lynch,684,Germany,Male,18,9,90544.00,1,0,1,4777.23,0
9501,9502,15634146,Hou,835,Germany,Male,18,2,142872.36,1,1,1,117632.63,0
4556,4557,15796231,Nwankwo,681,France,Female,18,1,98894.39,1,1,1,9596.40,0
9932,9933,15813451,Fleetwood-Smith,677,Spain,Male,18,8,134796.87,2,1,1,114858.90,0
3330,3331,15657439,Chao,738,France,Male,18,4,0.00,2,1,1,47799.15,0

También se puede ordenar por varias columnas:

In [ ]:
df_ordenado=df.sort_values(['Age', 'CreditScore'], ascending=[True, False])

In [ ]:
df_ordenado.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
746,747,15787619,Hsieh,844,France,Male,18,2,160980.03,1,0,0,145936.28,0
9501,9502,15634146,Hou,835,Germany,Male,18,2,142872.36,1,1,1,117632.63,0
3512,3513,15657779,Boylan,806,Spain,Male,18,3,0.00,2,1,1,86994.54,0
3517,3518,15757821,Burgess,771,Spain,Male,18,1,0.00,2,0,0,41542.95,0
3330,3331,15657439,Chao,738,France,Male,18,4,0.00,2,1,1,47799.15,0

In [ ]:
df_ordenado.reset_index(drop=False, inplace=True)

In [ ]:
df_ordenado.head()

,index,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,746,747,15787619,Hsieh,844,France,Male,18,2,160980.03,1,0,0,145936.28,0
1,9501,9502,15634146,Hou,835,Germany,Male,18,2,142872.36,1,1,1,117632.63,0
2,3512,3513,15657779,Boylan,806,Spain,Male,18,3,0.00,2,1,1,86994.54,0
3,3517,3518,15757821,Burgess,771,Spain,Male,18,1,0.00,2,0,0,41542.95,0
4,3330,3331,15657439,Chao,738,France,Male,18,4,0.00,2,1,1,47799.15,0

Podemos filtrar las columnas que queremos

In [ ]:
df['Age']

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [ ]:
df[['Age', 'CreditScore', 'Gender']]

      Age  CreditScore  Gender
0      42          619  Female
1      41          608  Female
2      42          502  Female
3      39          699  Female
4      43          850  Female
...   ...          ...     ...
9995   39          771    Male
9996   35          516    Male
9997   36          709  Female
9998   42          772    Male
9999   28          792  Female

[10000 rows x 3 columns]

In [ ]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

# para guardar una Copia de **seguridads** **texto en negrita**

In [ ]:
data = df.copy()

***data=df, no se usa, porque lo que haga en data, automaticmente se pasa a df y viceversa***

In [ ]:
data = df

Tambien podemos filtrar los menores de 30 de la siguiente forma:

In [ ]:
df[df['Geography']=='France']

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
(df['Age']<30).head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: Age, dtype: bool

In [ ]:
df[df['Age']!=30]    #No es igual a 30

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df[df['Age']==30]   #igual a 30

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
87,88,15625759,Rowley,729,France,Male,30,9,0.00,2,1,0,151869.35,0
110,111,15803526,Eremenko,685,Germany,Male,30,3,90536.81,1,0,1,63082.88,0
115,116,15675522,Ko,628,Germany,Female,30,9,132351.29,2,1,1,74169.13,0
161,162,15641122,Wei,684,France,Male,30,2,0.00,2,1,0,83473.82,0
173,174,15586310,Ting,578,France,Male,30,4,169462.09,1,1,0,112187.11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9817,9818,15812611,Lorimer,690,Spain,Female,30,5,0.00,2,0,1,78700.03,0
9842,9843,15746704,Jibunoh,638,Spain,Male,30,9,136808.53,2,1,1,106642.97,0
9860,9861,15716431,Brookes,775,France,Female,30,10,191091.74,2,1,1,96170.38,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0

In [ ]:
df[df['Age']<30]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9973,9974,15806455,Miller,611,France,Male,27,7,0.00,2,1,1,157474.10,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df[df['Geography']=="France"]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

Podemos filtrar los que son de origen Alemán

In [ ]:
df['Geography']=='Germany'

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998     True
9999    False
Name: Geography, Length: 10000, dtype: bool

In [ ]:
df[df['Geography']=='Germany']

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
28,29,15728693,McWilliams,574,Germany,Female,43,3,141349.43,1,1,1,100187.43,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9984,9985,15696175,Echezonachukwu,602,Germany,Male,35,7,90602.42,2,1,1,51695.41,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1

Y se pueden juntar las condiciones:

In [ ]:
df[(df['Age']<30) & (df['Geography']=='Germany')]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
46,47,15602280,Martin,829,Germany,Female,27,9,112045.67,1,1,1,119708.21,1
57,58,15647091,Endrizzi,725,Germany,Male,19,0,75888.20,1,0,0,45613.75,0
61,62,15773469,Clark,687,Germany,Female,27,9,152328.88,2,0,0,126494.82,0
64,65,15592461,Jackson,603,Germany,Male,26,4,109166.37,1,1,1,92840.67,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9825,9826,15701936,Bell,467,Germany,Male,28,10,126315.26,1,1,0,32349.29,1
9843,9844,15778304,Fan,646,Germany,Male,24,0,92398.08,1,1,1,18897.29,0
9851,9852,15792077,Degtyaryov,671,Germany,Male,28,8,119859.52,2,1,0,125422.66,0
9935,9936,15603454,Sanders,735,Germany,Male,28,5,160454.15,2,0,1,114957.22,0
9942,9943,15683007,Torode,739,Germany,Female,25,5,113113.12,1,1,0,129181.27,0

In [ ]:
df[(df['Age']<30) | (df['Geography']=='Germany')]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df[(df['Age']<30) & (df['Geography']=='Germany')]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
46,47,15602280,Martin,829,Germany,Female,27,9,112045.67,1,1,1,119708.21,1
57,58,15647091,Endrizzi,725,Germany,Male,19,0,75888.20,1,0,0,45613.75,0
61,62,15773469,Clark,687,Germany,Female,27,9,152328.88,2,0,0,126494.82,0
64,65,15592461,Jackson,603,Germany,Male,26,4,109166.37,1,1,1,92840.67,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9825,9826,15701936,Bell,467,Germany,Male,28,10,126315.26,1,1,0,32349.29,1
9843,9844,15778304,Fan,646,Germany,Male,24,0,92398.08,1,1,1,18897.29,0
9851,9852,15792077,Degtyaryov,671,Germany,Male,28,8,119859.52,2,1,0,125422.66,0
9935,9936,15603454,Sanders,735,Germany,Male,28,5,160454.15,2,0,1,114957.22,0
9942,9943,15683007,Torode,739,Germany,Female,25,5,113113.12,1,1,0,129181.27,0

In [ ]:
df[(df['Age']<30).isin(df['Geography']=='Germany')]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

Otra forma de hacer filtros es usando la función .isin()

In [ ]:
type('30')

str

In [ ]:
30+30

60

In [ ]:
'30'+'30'

'3030'

In [ ]:
'30'+30

TypeError: can only concatenate str (not "int") to str

In [ ]:
'30'*30

'303030303030303030303030303030303030303030303030303030303030'

In [ ]:
#type(30)

In [ ]:
df[df['Geography'].isin(['Germany', 'France'])]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

### Algunas funciones básicas

Las siguientes son algunos comandos básicos, se recomienda revisar la documentación para ver que detalles se pueden hacer en especifico

In [ ]:
# media de CreditScore
print(df['CreditScore'].mean())

650.5288

In [ ]:
# mediana de CreditScore
print(df['CreditScore'].median())

652.0

In [ ]:
# min de CreditScore
print(df['CreditScore'].min())

350

In [ ]:
df['CreditScore'].min()

350

In [ ]:
# max de CreditScore
print(df['CreditScore'].max())

850

In [ ]:
# varianza de CreditScore
print(df['CreditScore'].var())

9341.860156575705

In [ ]:
# std de CreditScore
print(df['CreditScore'].std())

96.65329873613061

In [ ]:
# sum de CreditScore
print(df['CreditScore'].sum())

6505288

In [ ]:
# quantile de CreditScore
print(df['CreditScore'].quantile(0.75))

718.0

In [ ]:
# media de varias columnas
print(df[['CreditScore', 'Age']].mean())

CreditScore    650.5288
Age             38.9218
dtype: float64

In [ ]:
round(df[['CreditScore', 'Age']].mean(),2)

CreditScore    650.53
Age             38.92
dtype: float64

## Conteo

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [ ]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [ ]:
df.Gender.value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [ ]:
# Cuando lo necesitamos ordenar
df['Geography'].value_counts(sort=True)

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [ ]:
# Cuando lo necesitamos ver como frecuencia relativa
df['Geography'].value_counts(normalize=True)

Geography
France     0.5014
Germany    0.2509
Spain      0.2477
Name: proportion, dtype: float64

## Group by

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.groupby('Geography')['CreditScore'].min()

Geography
France     350
Germany    350
Spain      350
Name: CreditScore, dtype: int64

In [ ]:
df.groupby('Geography')['CreditScore'].agg([min, max, sum])

/tmp/ipykernel_5175/389350033.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('Geography')['CreditScore'].agg([min, max, sum])
/tmp/ipykernel_5175/389350033.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('Geography')['CreditScore'].agg([min, max, sum])
/tmp/ipykernel_5175/389350033.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('Geography')['CreditScore'].agg([min, max, sum])

           min  max      sum
Geography
France     350  850  3257437
Germany    350  850  1634497
Spain      350  850  1613354

In [ ]:
import numpy as np
df.groupby('Geography')['CreditScore'].agg([min, max, sum, np.mean, np.median, np.std])

/tmp/ipykernel_5175/3765766939.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('Geography')['CreditScore'].agg([min, max, sum, np.mean, np.median, np.std])
/tmp/ipykernel_5175/3765766939.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('Geography')['CreditScore'].agg([min, max, sum, np.mean, np.median, np.std])
/tmp/ipykernel_5175/3765766939.py:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('Geography')['CreditScore'].agg([min, max, sum, np.mean, np.median, np.std])
/tmp/ipykernel_5175/3765766939.py:2: FutureWarning: The provided callable <function mean at 0x7da747b21800> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('Geography')['CreditScore'].agg([min, max, sum, np.mean, np.median, np.std])
/tmp/ipykernel_5175/3765766939.py:2: FutureWarning: The provided callable <function median at 0x7da747a75b20> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('Geography')['CreditScore'].agg([min, max, sum, np.mean, np.median, np.std])
/tmp/ipykernel_5175/3765766939.py:2: FutureWarning: The provided callable <function std at 0x7da747b21940> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  df.groupby('Geography')['CreditScore'].agg([min, max, sum, np.mean, np.median, np.std])

           min  max      sum        mean  median        std
Geography
France     350  850  3257437  649.668329   653.0  97.016799
Germany    350  850  1634497  651.453567   651.0  98.168937
Spain      350  850  1613354  651.333872   651.0  94.365051

Se puede agrupar por 2 características

In [ ]:
df.groupby(['Geography', 'Gender'])['CreditScore'].mean()

Geography  Gender
France     Female    649.185759
           Male      650.064657
Germany    Female    653.093881
           Male      649.966565
Spain      Female    651.769513
           Male      650.992075
Name: CreditScore, dtype: float64

También con varios aspectos:

In [ ]:
df.groupby(['Geography', 'Gender'])[['CreditScore', 'Age', 'Balance']].mean()

                  CreditScore        Age        Balance
Geography Gender
France    Female   649.185759  38.773994   60322.670159
          Male     650.064657  38.296404   63546.284875
Germany   Female   653.093881  40.154233  119145.966471
          Male     649.966565  39.424772  120259.668222
Spain     Female   651.769513  39.199265   59862.092534
          Male     650.992075  38.649135   63352.833746

## Tablas pivotes

Cuando queremos hacer tablas cruzadas, sería así:

In [ ]:
df.pivot_table(values='CreditScore', index='Geography', columns='Gender', aggfunc='mean')

Gender         Female        Male
Geography
France     649.185759  650.064657
Germany    653.093881  649.966565
Spain      651.769513  650.992075

In [ ]:
df.pivot_table(values='Exited', index='Geography', columns='Gender', aggfunc='count', fill_value=0, margins=True)

Gender     Female  Male    All
Geography
France       2261  2753   5014
Germany      1193  1316   2509
Spain        1089  1388   2477
All          4543  5457  10000

## Cambiar index

In [ ]:
df.head()

,RowNumber,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CustomerId,,,,,,,,,,,,,
15634602,1,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
15647311,2,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
15619304,3,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
15701354,4,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
15737888,5,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

Podemos tomar una columna como indice (no debe tener valores repetidos)

In [ ]:
df= df.set_index('CustomerId')

In [ ]:
df= df.set_index()

TypeError: DataFrame.set_index() missing 1 required positional argument: 'keys'

In [ ]:
df.head()

,RowNumber,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CustomerId,,,,,,,,,,,,,
15634602,1,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
15647311,2,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
15619304,3,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
15701354,4,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
15737888,5,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

Si lo queremos ordenar con el index

In [ ]:
df.sort_index()
df.head()

,RowNumber,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CustomerId,,,,,,,,,,,,,
15634602,1,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
15647311,2,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
15619304,3,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
15701354,4,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
15737888,5,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

Para remover el proceso, se hace lo siguiente:

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df.head()

,CustomerId,RowNumber,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,1,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,2,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,3,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,4,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,5,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

## Slicing

Para esto se usa loc y iloc

In [ ]:
col_names = ['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited']

In [ ]:
col_names[2:5]

['Surname', 'CreditScore', 'Geography']

In [ ]:
col_names[:5]

['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography']

In [ ]:
col_names[5:]

['Gender',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Exited']

In [ ]:
df_pivot = df.pivot_table(values='CreditScore', index='Age', columns='Geography', aggfunc='mean', fill_value=0)
df_pivot

Geography      France     Germany       Spain
Age
18         669.727273  699.666667  708.400000
19         680.545455  620.375000  690.375000
20         674.142857  656.166667  654.461538
21         642.387097  675.454545  632.909091
22         627.266667  653.545455  644.785714
..                ...         ...         ...
83           0.000000  678.000000    0.000000
84         408.000000  537.000000    0.000000
85         787.000000    0.000000    0.000000
88           0.000000    0.000000  513.000000
92         729.000000    0.000000    0.000000

[70 rows x 3 columns]

Podemos filtrar las filas, en este caso de la 22 a la 35

In [ ]:
df_pivot.loc[22:35]

Geography      France     Germany       Spain
Age
22         627.266667  653.545455  644.785714
23         671.177778  639.629630  653.592593
24         668.205479  626.592593  643.500000
25         650.594203  628.446809  646.473684
26         646.194690  654.581395  649.772727
27         639.181034  677.704545  619.836735
28         665.022222  653.057971  644.927536
29         650.076531  655.602740  657.670886
30         652.220930  652.419753  648.824324
31         653.637615  657.011494  649.353535
32         654.167421  653.770000  645.711340
33         644.072340  666.388350  658.913462
34         652.951417  659.714286  637.834862
35         635.043478  648.787611  649.625954

Podemos filtrar también por columnas

In [ ]:
df_pivot.loc[28:35, "Germany": "Spain"]

Geography     Germany       Spain
Age
28         653.057971  644.927536
29         655.602740  657.670886
30         652.419753  648.824324
31         657.011494  649.353535
32         653.770000  645.711340
33         666.388350  658.913462
34         659.714286  637.834862
35         648.787611  649.625954

La opción de iloc usa los valores numéricos a los que corresponde

In [ ]:
df_pivot.iloc[10:18, 1: ]

Geography     Germany       Spain
Age
28         653.057971  644.927536
29         655.602740  657.670886
30         652.419753  648.824324
31         657.011494  649.353535
32         653.770000  645.711340
33         666.388350  658.913462
34         659.714286  637.834862
35         648.787611  649.625954